### ISSUE TITLE
Further development of the playable characters 

### ISSUE THREAD

**Issue by LukeT23** [kaiwilens/Python_text-based_game#16]
We have a good base for the NPC's and playable characters. We need to add determine what other functions the playable characters need and what would be the best way to implement them.

**Comment by Brandon-Perry358** [comment]
I know for certain that we will want to add magic to the character class in some way. We would need magic points stats for them. For non-mage classes, this would be zero. Perhaps I can speak with Kai to see if we can connect his inventory system to the character class, so that we can have the size of the inventory dictated by a stat, and maybe different characters can have different size inventories from the start.

**Comment by Brandon-Perry358** [comment]
And a level stat that we can use to raise character's stats when they progress.

**Comment by kaiwilens** [comment]
I'll be available to help out with that implementation.

**Comment by Brandon-Perry358** [comment]
That would be much appreciated. Sorry I haven't had the chance to do it myself. I've been working on the job system still, amongst other things.

**Comment by LukeT23** [comment]
I think what might work is if magical objects have a boolean function of
"has_magic" or something. I can add the same boolean to the character class
along with a get function so then when the character tries to equip the
magical object the equip code for the magical objects can call the
get_has_magic() function.

**Comment by Brandon-Perry358** [comment]
The trouble with that is that some characters themselves will have magic points, while others won't, not just items. I do like the idea that certain items can boost stats though.

**Comment by LukeT23** [comment]
Oh no I totally get that. I meant using the boolean for the purpose of
equipping magical items and giving magical characters the points. The
character class would be set up to where whoever is creating the characters
will put in if they are magical and if they are not it would have the magic
points set to a constant 0.

**Comment by Brandon-Perry358** [comment]
Ohhhhhh okay, I gotcha

**Comment by LukeT23** [comment]
Hey guys when you get the chance can you check out the new code I added for the characters? I think at this point we have as much as we can have with out knowing the story specifics and what the characters need.

**Comment by kaiwilens** [comment]
Since I've seen a lot of progress on this, I'm gonna close this issue. Please let me know if I should reopen it.
