### ISSUE TITLE
Look into P2P Multiplayer

### ISSUE THREAD

**Issue by dagan-poulin** [kaiwilens/Python_text-based_game#2]
Look into what it may take to do a Point to Point multiplayer, and how python may handle an asynchronous input.
Further, see if there's a way to link any currently developed systems into easy-to-parse packets.

**Comment by dagan-poulin** [comment]
I've found a resource on networking with sockets in Python. Actually looks rather doable, especially if the game is Asynchronous in any way. We'll need to develop a format to send the user information over, though, for easier processing. 

Still TBD if we want to do multiplayer.
Resources:
https://www.tutorialspoint.com/python/python_networking.htm

**Comment by kaiwilens** [comment]
Good job!

**Comment by dagan-poulin** [comment]
This wouldn't be practical.
