### ISSUE TITLE
Modify Experience and Level up functions

### ISSUE THREAD

**Issue by LukeT23** [kaiwilens/Python_text-based_game#23]
The functions used for the character to gain experience and level up need to be modified so that if the character gains enough experience in one battle to level up more than once the function continues leveling them up until their experience is less than the required experience for the next level.

**Comment by kaiwilens** [comment]
I'll look over the code and once I have a better understanding of it, I'll see what I can do to help. @LukeT23

**Comment by LukeT23** [comment]
I have improved these codes with my most recent pull request and this is no longer an issue!
