### ISSUE TITLE
Decide a Title

### ISSUE THREAD

**Issue by Brandon-Perry358** [kaiwilens/Python_text-based_game#25]
I really like Temporal Crisis or Temporal Duality. If you guys have any ideas, throw em in here and we can vote on it.

**Comment by Ghraam** [comment]
I think that "Temporal Crisis" sounds good. No one seems to be on board with my idea of "🖲🤖🥢💾🧠".

**Comment by kaiwilens** [comment]
I like the sound of "Temporal crisis" for the name of the game!

**Comment by kaiwilens** [comment]
I'm gonna close this issue since we said that **_Temporal Duality_** was a good name for the game.
