### ISSUE TITLE
Code Clean/Tweak Up

### ISSUE THREAD

**Issue by kaiwilens** [kaiwilens/Python_text-based_game#26]
I finally got the chance to take a look at the python code files this week. I'm still trying to get a better understanding of the code but I did notice some things in the code that could be tweaked a little bit.  

**Disclaimer: I'm NOT saying that this code is bad by the way. Whoever made the code is doing a better job than I am right now.** 

**For example:** 
![edit code](https://user-images.githubusercontent.com/59850413/110700792-5c76f000-81be-11eb-8821-49d506bda8f9.PNG)

**I wouldn't mind tweaking it into this which I think looks much clearer when reading the code:** 
![clean code](https://user-images.githubusercontent.com/59850413/110701142-cc857600-81be-11eb-8023-3416e8445e08.PNG)

Just add yourself to the assignees if you're interested. ^_^

**Comment by LukeT23** [comment]
I am thinking something that we could do is add a function to the helper_functions file where we pass in the string, the function gets the length of the string and then prints the string along with (! * length) at the top and bottom that way it can be consistent.

**Comment by kaiwilens** [comment]
Closing issue after submitting new function.
