### ISSUE TITLE
Set up initial python files

### ISSUE THREAD

**Issue by kaiwilens** [kaiwilens/Python_text-based_game#4]
Start to set up some basic python files (ex. main, player stats, enemy stats, inventory, etc). They don't need to have any code in them but this will give us a better outline of the number of files we should have to start out. 

**Here's a picture of what I mean:** 
![file examples](https://user-images.githubusercontent.com/59850413/109043064-edb67480-769e-11eb-8098-b411e787bf65.PNG)

**Tip:** Before you start doing any coding, write out your ideas on how the code you plan to use will work.

**Comment by LukeT23** [comment]
Files have been added to the repo.
