### ISSUE TITLE
Title screen/ Main menu

### ISSUE THREAD

**Issue by dagan-poulin** [kaiwilens/Python_text-based_game#43]
I don't know how long we've gone, talking about needing a title screen, without opening an issue for a title screen.

Here's the issue for that.

**Comment by Brandon-Perry358** [comment]
I do have a concept for a basic title screen in the script which you guys can look at. We also now know that the title of the game is Temporal Duality, so the only thing we would need to create would be some ASCII art for the title screen, and then actually write it in code if that hasn't already happened.
